version: '3.8'

services:
  db:
    restart: always
    image: postgres:13
    container_name: BD_STATIONS_API
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  app:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build:
      context: "./app"
      dockerfile: Dockerfile
    container_name: STATIONS_API
    env_file: ".env"
    ports:
      - "8000:8000"
  

#  app:
#    build: .
 #   depends_on:
  #    - db
   # environment:
    #  - DATABASE_URL=${DATABASE_URL}
   # ports:
    #  - "8000:8000"
    #volumes:
     # - .:/app

volumes:
  postgres_data:
